//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <Vcl.Controls.hpp>
#include <Vcl.StdCtrls.hpp>
#include <Vcl.Forms.hpp>
#include <Vcl.ComCtrls.hpp>
#include <Vcl.Buttons.hpp>
#include <Vcl.ExtCtrls.hpp>
#include <FileCtrl.hpp>
#include <Vcl.Mask.hpp>
#include <Vcl.Dialogs.hpp>
#include <Vcl.ImgList.hpp>
#include <shlwapi.h>
#include <shlobj.h>
#include <IniFiles.hpp>
#include "Unit4.h"
#include <Vcl.Grids.hpp>
#include <Vcl.ValEdit.hpp>
#include <Vcl.CheckLst.hpp>
#include "perfgrap.h";
#include <mmsystem.h>
#include <dsound.h>
#include <System.Math.hpp>
#include "..\\upconv_src\\upconv\\upconv.h"
#include "..\\upconv_src\\PLG_AUDIO_IO\\PLG_AudioIO.h"


#define BUFFER_FREE			1
#define BUFFER_CONVERT		2
#define BUFFER_READY		3
#define BUFFER_PLAY			4
#define BUFFER_PLAY_DONE	5

typedef struct tagSOUND_BUFFER {
	WAVEHDR 	whdr;
	AnsiString 	file_name;
	AnsiString  fin_file_name;
	int			fn_number;
	int			status;
	int			offset;
	int			sec;
} SOUND_BUFFER;

typedef struct {
	double x;
	double y;
} PT2D;

//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE で管理されるコンポーネント
	TPageControl *pageMain;
	TTabSheet *tabUpconv;
	TLabel *Label1;
	TListView *LvFile;
	TBitBtn *btnAdd;
	TBitBtn *btnDel;
	TBitBtn *btnClear;
	TBitBtn *btnUp;
	TBitBtn *btnDown;
	TTabSheet *tabAnalyze;
	TLabel *Label2;
	TGroupBox *GroupBox7;
	TComboBox *cmbEQParameter;
	TBevel *Bevel2;
	TLabel *Label3;
	TGroupBox *GroupBox8;
	TGroupBox *GroupBox9;
	TButtonedEdit *edtOutputPath;
	TOpenDialog *OpenDialog;
	TImageList *ImageList1;
	TImageList *ImageList2;
	TTimer *Timer1;
	TBevel *Bevel6;
	TBitBtn *btnExit;
	TBitBtn *btnAbort;
	TBitBtn *btnStart;
	TProgressBar *prgExec;
	TLabel *lbl_exec_status;
	TLabel *lbl_count;
	TButtonedEdit *edtSuffix;
	TLabel *lbl_co;
	TLabel *lbl_select_directory;
	TBitBtn *btnPause;
	TBitBtn *btnLoad;
	TButton *btn_Load;
	TPageControl *PageEQ;
	TTabSheet *EQ_Type1;
	TTabSheet *EQ_Type2;
	TTabSheet *EQ_Type3;
	TGroupBox *GroupBox3;
	TGroupBox *GroupBox10;
	TPanel *Panel1;
	TEdit *edt_eq_title;
	TBitBtn *btn_eq_save;
	TScrollBox *t2_scrbox;
	TPanel *Panel2;
	TTrackBar *TB_2_1;
	TTrackBar *TB_2_2;
	TTrackBar *TB_2_3;
	TTrackBar *TB_2_4;
	TTrackBar *TB_2_5;
	TTrackBar *TB_2_6;
	TTrackBar *TB_2_7;
	TTrackBar *TB_2_8;
	TTrackBar *TB_2_9;
	TTrackBar *TB_2_10;
	TTrackBar *TB_2_11;
	TTrackBar *TB_2_12;
	TTrackBar *TB_2_13;
	TTrackBar *TB_2_14;
	TTrackBar *TB_2_15;
	TTrackBar *TB_2_16;
	TTrackBar *TB_2_17;
	TLabel *Label114;
	TLabel *Label121;
	TLabel *Label122;
	TLabel *Label115;
	TLabel *Label123;
	TLabel *Label124;
	TLabel *Label116;
	TLabel *Label125;
	TLabel *Label126;
	TLabel *Label117;
	TLabel *Label127;
	TLabel *Label128;
	TLabel *Label118;
	TLabel *Label129;
	TLabel *Label130;
	TLabel *Label119;
	TLabel *Label120;
	TTrackBar *TB_2_18;
	TLabel *Label131;
	TLabel *Label138;
	TTrackBar *TB_2_19;
	TTrackBar *TB_2_20;
	TLabel *Label139;
	TLabel *Label132;
	TTrackBar *TB_2_21;
	TTrackBar *TB_2_22;
	TLabel *Label140;
	TLabel *Label141;
	TTrackBar *TB_2_23;
	TTrackBar *TB_2_24;
	TLabel *Label133;
	TLabel *Label142;
	TTrackBar *TB_2_25;
	TTrackBar *TB_2_26;
	TLabel *Label143;
	TLabel *Label134;
	TTrackBar *TB_2_27;
	TTrackBar *TB_2_28;
	TLabel *Label144;
	TLabel *Label145;
	TTrackBar *TB_2_29;
	TTrackBar *TB_2_30;
	TLabel *Label135;
	TLabel *Label146;
	TTrackBar *TB_2_31;
	TTrackBar *TB_2_32;
	TLabel *Label147;
	TLabel *Label136;
	TTrackBar *TB_2_33;
	TTrackBar *TB_2_34;
	TLabel *Label137;
	TTrackBar *TB_2_35;
	TLabel *Label148;
	TLabel *Label155;
	TTrackBar *TB_2_36;
	TTrackBar *TB_2_37;
	TLabel *Label156;
	TLabel *Label149;
	TTrackBar *TB_2_38;
	TTrackBar *TB_2_39;
	TLabel *Label157;
	TLabel *Label158;
	TTrackBar *TB_2_40;
	TTrackBar *TB_2_41;
	TLabel *Label150;
	TLabel *Label159;
	TTrackBar *TB_2_42;
	TTrackBar *TB_2_43;
	TLabel *Label160;
	TLabel *Label151;
	TTrackBar *TB_2_44;
	TTrackBar *TB_2_45;
	TLabel *Label161;
	TLabel *Label162;
	TTrackBar *TB_2_46;
	TTrackBar *TB_2_47;
	TLabel *Label152;
	TLabel *Label163;
	TTrackBar *TB_2_48;
	TTrackBar *TB_2_49;
	TLabel *Label164;
	TLabel *Label153;
	TTrackBar *TB_2_50;
	TLabel *eq_2_1;
	TLabel *eq_2_2;
	TLabel *eq_2_3;
	TLabel *eq_2_4;
	TLabel *eq_2_5;
	TLabel *eq_2_6;
	TLabel *eq_2_7;
	TLabel *eq_2_8;
	TLabel *eq_2_9;
	TLabel *eq_2_10;
	TLabel *eq_2_11;
	TLabel *eq_2_12;
	TLabel *eq_2_13;
	TLabel *eq_2_14;
	TLabel *eq_2_15;
	TLabel *eq_2_16;
	TLabel *eq_2_17;
	TLabel *eq_2_18;
	TLabel *eq_2_19;
	TLabel *eq_2_20;
	TLabel *eq_2_21;
	TLabel *eq_2_22;
	TLabel *eq_2_23;
	TLabel *eq_2_24;
	TLabel *eq_2_25;
	TLabel *eq_2_26;
	TLabel *eq_2_27;
	TLabel *eq_2_28;
	TLabel *eq_2_29;
	TLabel *eq_2_30;
	TLabel *eq_2_31;
	TLabel *eq_2_32;
	TLabel *eq_2_33;
	TLabel *eq_2_34;
	TLabel *eq_2_35;
	TLabel *eq_2_50;
	TLabel *eq_2_49;
	TLabel *eq_2_48;
	TLabel *eq_2_47;
	TLabel *eq_2_46;
	TLabel *eq_2_45;
	TLabel *eq_2_44;
	TLabel *eq_2_43;
	TLabel *eq_2_42;
	TLabel *eq_2_41;
	TLabel *eq_2_40;
	TLabel *eq_2_39;
	TLabel *eq_2_38;
	TLabel *eq_2_37;
	TLabel *eq_2_36;
	TButton *btn_type2_all_down;
	TButton *btn_type2_all_center;
	TButton *btn_type2_all_up;
	TButton *btn_type2_copy_from_type1;
	TScrollBox *t3_scrbox;
	TPanel *Panel4;
	TTrackBar *TB_3_1;
	TTrackBar *TB_3_2;
	TTrackBar *TB_3_3;
	TTrackBar *TB_3_4;
	TTrackBar *TB_3_5;
	TTrackBar *TB_3_6;
	TTrackBar *TB_3_7;
	TTrackBar *TB_3_8;
	TTrackBar *TB_3_9;
	TTrackBar *TB_3_10;
	TTrackBar *TB_3_11;
	TTrackBar *TB_3_12;
	TTrackBar *TB_3_13;
	TTrackBar *TB_3_14;
	TTrackBar *TB_3_15;
	TTrackBar *TB_3_16;
	TTrackBar *TB_3_17;
	TTrackBar *TB_3_18;
	TLabel *Label18;
	TLabel *Label56;
	TLabel *Label57;
	TLabel *Label58;
	TLabel *Label19;
	TLabel *Label20;
	TLabel *Label21;
	TLabel *Label22;
	TLabel *Label23;
	TLabel *Label26;
	TLabel *Label59;
	TLabel *Label60;
	TLabel *Label61;
	TLabel *Label62;
	TLabel *Label63;
	TLabel *Label64;
	TLabel *Label65;
	TLabel *Label66;
	TTrackBar *TB_3_19;
	TTrackBar *TB_3_20;
	TTrackBar *TB_3_21;
	TTrackBar *TB_3_22;
	TTrackBar *TB_3_23;
	TTrackBar *TB_3_24;
	TTrackBar *TB_3_25;
	TTrackBar *TB_3_26;
	TTrackBar *TB_3_27;
	TTrackBar *TB_3_28;
	TTrackBar *TB_3_29;
	TTrackBar *TB_3_30;
	TTrackBar *TB_3_31;
	TTrackBar *TB_3_32;
	TTrackBar *TB_3_33;
	TTrackBar *TB_3_34;
	TTrackBar *TB_3_35;
	TTrackBar *TB_3_36;
	TLabel *Label27;
	TLabel *Label67;
	TLabel *Label68;
	TLabel *Label28;
	TLabel *Label29;
	TLabel *Label30;
	TLabel *Label31;
	TLabel *Label32;
	TLabel *Label33;
	TLabel *Label69;
	TLabel *Label70;
	TLabel *Label71;
	TLabel *Label72;
	TLabel *Label73;
	TLabel *Label74;
	TLabel *Label75;
	TLabel *Label76;
	TLabel *Label77;
	TTrackBar *TB_3_37;
	TLabel *Label78;
	TLabel *Label80;
	TTrackBar *TB_3_38;
	TTrackBar *TB_3_39;
	TLabel *Label81;
	TLabel *Label79;
	TTrackBar *TB_3_40;
	TTrackBar *TB_3_41;
	TLabel *Label82;
	TLabel *Label83;
	TTrackBar *TB_3_42;
	TTrackBar *TB_3_43;
	TLabel *Label84;
	TLabel *Label85;
	TTrackBar *TB_3_44;
	TTrackBar *TB_3_45;
	TLabel *Label86;
	TLabel *Label87;
	TTrackBar *TB_3_46;
	TTrackBar *TB_3_47;
	TLabel *Label88;
	TLabel *Label89;
	TTrackBar *TB_3_48;
	TTrackBar *TB_3_49;
	TLabel *Label90;
	TLabel *Label91;
	TTrackBar *TB_3_50;
	TTrackBar *TB_3_51;
	TLabel *Label92;
	TLabel *Label93;
	TTrackBar *TB_3_52;
	TTrackBar *TB_3_53;
	TLabel *Label94;
	TLabel *Label95;
	TTrackBar *TB_3_54;
	TTrackBar *TB_3_55;
	TLabel *Label96;
	TLabel *Label98;
	TTrackBar *TB_3_56;
	TTrackBar *TB_3_57;
	TLabel *Label99;
	TLabel *Label97;
	TTrackBar *TB_3_58;
	TTrackBar *TB_3_59;
	TLabel *Label100;
	TLabel *Label101;
	TTrackBar *TB_3_60;
	TTrackBar *TB_3_61;
	TLabel *Label102;
	TLabel *Label103;
	TTrackBar *TB_3_62;
	TTrackBar *TB_3_63;
	TLabel *Label104;
	TLabel *Label105;
	TTrackBar *TB_3_64;
	TTrackBar *TB_3_65;
	TLabel *Label106;
	TLabel *Label107;
	TTrackBar *TB_3_66;
	TTrackBar *TB_3_67;
	TLabel *Label108;
	TLabel *Label109;
	TTrackBar *TB_3_68;
	TTrackBar *TB_3_69;
	TLabel *Label110;
	TLabel *Label111;
	TTrackBar *TB_3_70;
	TTrackBar *TB_3_71;
	TLabel *Label112;
	TLabel *Label113;
	TTrackBar *TB_3_72;
	TLabel *eq_3_1;
	TLabel *eq_3_2;
	TLabel *eq_3_3;
	TLabel *eq_3_4;
	TLabel *eq_3_5;
	TLabel *eq_3_6;
	TLabel *eq_3_7;
	TLabel *eq_3_8;
	TLabel *eq_3_9;
	TLabel *eq_3_10;
	TLabel *eq_3_11;
	TLabel *eq_3_12;
	TLabel *eq_3_13;
	TLabel *eq_3_14;
	TLabel *eq_3_15;
	TLabel *eq_3_16;
	TLabel *eq_3_17;
	TLabel *eq_3_18;
	TLabel *eq_3_19;
	TLabel *eq_3_20;
	TLabel *eq_3_21;
	TLabel *eq_3_22;
	TLabel *eq_3_23;
	TLabel *eq_3_24;
	TLabel *eq_3_25;
	TLabel *eq_3_26;
	TLabel *eq_3_27;
	TLabel *eq_3_28;
	TLabel *eq_3_29;
	TLabel *eq_3_30;
	TLabel *eq_3_31;
	TLabel *eq_3_32;
	TLabel *eq_3_33;
	TLabel *eq_3_34;
	TLabel *eq_3_35;
	TLabel *eq_3_36;
	TLabel *eq_3_37;
	TLabel *eq_3_38;
	TLabel *eq_3_39;
	TLabel *eq_3_40;
	TLabel *eq_3_41;
	TLabel *eq_3_42;
	TLabel *eq_3_43;
	TLabel *eq_3_44;
	TLabel *eq_3_45;
	TLabel *eq_3_46;
	TLabel *eq_3_47;
	TLabel *eq_3_48;
	TLabel *eq_3_49;
	TLabel *eq_3_50;
	TLabel *eq_3_51;
	TLabel *eq_3_52;
	TLabel *eq_3_53;
	TLabel *eq_3_54;
	TLabel *eq_3_55;
	TLabel *eq_3_56;
	TLabel *eq_3_57;
	TLabel *eq_3_58;
	TLabel *eq_3_59;
	TLabel *eq_3_60;
	TLabel *eq_3_61;
	TLabel *eq_3_62;
	TLabel *eq_3_63;
	TLabel *eq_3_64;
	TLabel *eq_3_65;
	TLabel *eq_3_66;
	TLabel *eq_3_67;
	TLabel *eq_3_68;
	TLabel *eq_3_69;
	TLabel *eq_3_70;
	TTrackBar *TB_3_73;
	TTrackBar *TB_3_74;
	TTrackBar *TB_3_75;
	TLabel *Label154;
	TLabel *Label165;
	TLabel *Label166;
	TLabel *Label167;
	TTrackBar *TB_3_76;
	TTrackBar *TB_3_77;
	TLabel *Label168;
	TLabel *Label169;
	TTrackBar *TB_3_78;
	TLabel *eq_3_71;
	TLabel *eq_3_72;
	TLabel *eq_3_73;
	TLabel *eq_3_74;
	TLabel *eq_3_75;
	TLabel *eq_3_76;
	TLabel *eq_3_77;
	TLabel *eq_3_78;
	TButton *btn_type3_all_center;
	TButton *btn_type3_all_up;
	TButton *btn_type3_all_down;
	TButton *btn_type3_copy_from_type2;
	TSaveDialog *SaveDialog1;
	TOpenDialog *OpenDialog1;
	TBitBtn *btn_eq_delete;
	TLabel *Label170;
	TLabel *Label171;
	TLabel *Label172;
	TLabel *Label174;
	TRadioButton *rdo_type2_value_x1;
	TRadioButton *rdo_type2_value_x2;
	TGroupBox *GroupBox1;
	TLabel *Label173;
	TScrollBox *t1_scrbox;
	TPanel *Panel3;
	TLabel *eq_1_1;
	TLabel *eq_1_2;
	TLabel *eq_1_3;
	TLabel *eq_1_4;
	TLabel *eq_1_5;
	TLabel *eq_1_6;
	TLabel *eq_1_7;
	TLabel *eq_1_8;
	TLabel *eq_1_9;
	TLabel *eq_1_10;
	TLabel *eq_1_11;
	TLabel *eq_1_12;
	TLabel *eq_1_13;
	TLabel *eq_1_14;
	TLabel *eq_1_15;
	TLabel *eq_1_16;
	TLabel *eq_1_17;
	TLabel *Label4;
	TLabel *Label35;
	TLabel *Label36;
	TLabel *Label5;
	TLabel *Label37;
	TLabel *Label38;
	TLabel *Label6;
	TLabel *Label39;
	TLabel *Label40;
	TLabel *Label10;
	TLabel *Label41;
	TLabel *Label42;
	TLabel *Label11;
	TLabel *Label43;
	TLabel *Label44;
	TLabel *Label12;
	TLabel *Label24;
	TLabel *eq_1_18;
	TLabel *eq_1_19;
	TLabel *eq_1_20;
	TLabel *eq_1_21;
	TLabel *eq_1_22;
	TLabel *eq_1_23;
	TLabel *eq_1_24;
	TLabel *eq_1_25;
	TLabel *eq_1_26;
	TLabel *eq_1_27;
	TLabel *eq_1_28;
	TLabel *eq_1_29;
	TLabel *eq_1_30;
	TLabel *eq_1_31;
	TLabel *eq_1_32;
	TLabel *eq_1_33;
	TLabel *eq_1_34;
	TLabel *eq_1_35;
	TLabel *Label7;
	TLabel *Label45;
	TLabel *Label46;
	TLabel *Label8;
	TLabel *Label47;
	TLabel *Label48;
	TLabel *Label14;
	TLabel *Label49;
	TLabel *Label50;
	TLabel *Label16;
	TLabel *Label51;
	TLabel *Label52;
	TLabel *Label17;
	TLabel *Label53;
	TLabel *Label54;
	TLabel *Label9;
	TLabel *Label55;
	TLabel *Label25;
	TLabel *Label34;
	TTrackBar *TB_1_1;
	TTrackBar *TB_1_2;
	TTrackBar *TB_1_3;
	TTrackBar *TB_1_4;
	TTrackBar *TB_1_5;
	TTrackBar *TB_1_6;
	TTrackBar *TB_1_7;
	TTrackBar *TB_1_8;
	TTrackBar *TB_1_9;
	TTrackBar *TB_1_10;
	TTrackBar *TB_1_11;
	TTrackBar *TB_1_12;
	TTrackBar *TB_1_13;
	TTrackBar *TB_1_14;
	TTrackBar *TB_1_15;
	TTrackBar *TB_1_16;
	TTrackBar *TB_1_17;
	TTrackBar *TB_1_18;
	TTrackBar *TB_1_19;
	TTrackBar *TB_1_20;
	TTrackBar *TB_1_21;
	TTrackBar *TB_1_22;
	TTrackBar *TB_1_23;
	TTrackBar *TB_1_24;
	TTrackBar *TB_1_25;
	TTrackBar *TB_1_26;
	TTrackBar *TB_1_27;
	TTrackBar *TB_1_28;
	TTrackBar *TB_1_29;
	TTrackBar *TB_1_30;
	TTrackBar *TB_1_31;
	TTrackBar *TB_1_32;
	TTrackBar *TB_1_33;
	TTrackBar *TB_1_34;
	TTrackBar *TB_1_35;
	TButton *btn_type1_all_center;
	TButton *btn_type1_all_up;
	TButton *btn_type1_all_down;
	TRadioButton *rdo_type1_value_x1;
	TRadioButton *rdo_type1_value_x2;
	TLabel *Label175;
	TRadioButton *rdo_type3_value_x1;
	TRadioButton *rdo_type3_value_x2;
	TGroupBox *GroupBox4;
	TButton *btnPlay;
	TTrackBar *track_skip_position;
	TLabel *lbl_time;
	TLabel *lbl_selected_len;
	TCheckBox *chk_play_loop;
	TTimer *Timer2;
	TLabel *Label15;
	TListView *LvAnaFile;
	TBitBtn *btn_ana_add;
	TBitBtn *btnAnaDel;
	TBitBtn *btnAnaClear;
	TBitBtn *btnAnaUp;
	TBitBtn *btnAnaDown;
	TBevel *Bevel3;
	TLabel *Label176;
	TGroupBox *GroupBox12;
	TComboBox *cmbEQ_Analyze;
	TButton *btn_EQ_Set;
	TMemo *edtParameter;
	TRadioButton *rdo_Analyze_Phase1;
	TRadioButton *rdo_Analyze_Phase2;
	TRadioButton *rdo_Analyze_Phase3;
	TMemo *memo_log;
	TMemo *memo_DeviceInfo;
	TBevel *Bevel4;
	TBevel *Bevel5;
	TBevel *Bevel7;
	TBevel *Bevel8;
	TBevel *Bevel9;
	TBevel *Bevel10;
	TComboBox *cmb_preview_length;
	TGroupBox *GroupBox6;
	TTabSheet *Option;
	TCategoryPanelGroup *CategoryPanelGroup1;
	TCategoryPanel *CategoryPanel1;
	TCategoryPanel *CategoryPanel2;
	TLabel *Label178;
	TLabel *Label179;
	TComboBox *cmbOutputFormat;
	TLabel *Label180;
	TComboBox *cmbEncoder;
	TLabel *Label13;
	TGroupBox *GroupBox13;
	TComboBox *cmbPlayDevice;
	TCheckBox *chk_44100;
	TCheckBox *chk_48000;
	TCheckBox *chk_96000;
	TGroupBox *GroupBox11;
	TRadioButton *rdo_preview_rate_44100;
	TRadioButton *rdo_preview_rate_48000;
	TRadioButton *rdo_preview_rate_96000;
	TBevel *Bevel11;
	TLabel *Label181;
	TLabel *Label182;
	TComboBox *cmbThread;
	TLabel *Label183;
	TComboBox *cmbPriority;
	TLabel *Label184;
	TComboBox *cmbFileIO;
	TBevel *Bevel12;
	TLabel *Label185;
	TButtonedEdit *be_log;
	TRadioButton *rdo_log_disable;
	TRadioButton *rdo_log_enable;
	TTimer *Timer3;
	TTimer *Timer4;
	TGroupBox *GroupBox2;
	TRadioButton *rdo_window_size1;
	TRadioButton *rdo_window_size2;
	TRadioButton *rdo_window_size3;
	TEdit *edtVInformation;
	TLabel *Label186;
	TComboBox *cmbADDP;
	TLabel *Label188;
	TLabel *lbl_play_set_device;
	TComboBox *cmb_volume_level;
	TEdit *edtFileSize;
	TComboBox *cmbNormalize;
	TLabel *Label177;
	TTabSheet *EQ_Type4;
	TGroupBox *GroupBox5;
	TLabel *Label187;
	TScrollBox *t4_scrbox;
	TPanel *Panel5;
	TLabel *l4_1;
	TLabel *l4_2;
	TLabel *l4_3;
	TLabel *l4_4;
	TLabel *l4_5;
	TLabel *l4_6;
	TLabel *l4_7;
	TLabel *l4_8;
	TLabel *l4_9;
	TLabel *l4_10;
	TLabel *l4_11;
	TLabel *l4_12;
	TLabel *l4_13;
	TLabel *l4_14;
	TLabel *l4_15;
	TLabel *l4_16;
	TLabel *l4_17;
	TLabel *l4_18;
	TLabel *l4_19;
	TLabel *l4_20;
	TLabel *l4_21;
	TLabel *l4_22;
	TLabel *l4_23;
	TLabel *l4_24;
	TLabel *l4_25;
	TLabel *l4_26;
	TLabel *l4_27;
	TLabel *l4_28;
	TLabel *l4_29;
	TLabel *l4_30;
	TLabel *l4_31;
	TLabel *l4_32;
	TLabel *l4_33;
	TLabel *l4_34;
	TLabel *l4_35;
	TLabel *l4_36;
	TLabel *l4_37;
	TLabel *l4_38;
	TLabel *l4_39;
	TLabel *l4_40;
	TLabel *l4_41;
	TLabel *l4_42;
	TLabel *l4_43;
	TLabel *l4_44;
	TLabel *l4_45;
	TLabel *l4_46;
	TLabel *l4_47;
	TLabel *l4_48;
	TLabel *l4_49;
	TLabel *l4_50;
	TLabel *l4_51;
	TLabel *l4_52;
	TLabel *l4_53;
	TLabel *l4_54;
	TLabel *l4_55;
	TLabel *l4_56;
	TLabel *l4_57;
	TLabel *l4_58;
	TLabel *l4_59;
	TLabel *l4_60;
	TLabel *l4_61;
	TLabel *l4_62;
	TLabel *l4_63;
	TLabel *l4_64;
	TLabel *l4_65;
	TLabel *l4_66;
	TLabel *l4_67;
	TLabel *l4_68;
	TLabel *l4_69;
	TLabel *l4_70;
	TLabel *l4_71;
	TLabel *l4_72;
	TLabel *eq_4_1;
	TLabel *eq_4_2;
	TLabel *eq_4_3;
	TLabel *eq_4_4;
	TLabel *eq_4_5;
	TLabel *eq_4_6;
	TLabel *eq_4_7;
	TLabel *eq_4_8;
	TLabel *eq_4_9;
	TLabel *eq_4_10;
	TLabel *eq_4_11;
	TLabel *eq_4_12;
	TLabel *eq_4_13;
	TLabel *eq_4_14;
	TLabel *eq_4_15;
	TLabel *eq_4_16;
	TLabel *eq_4_17;
	TLabel *eq_4_18;
	TLabel *eq_4_19;
	TLabel *eq_4_20;
	TLabel *eq_4_21;
	TLabel *eq_4_22;
	TLabel *eq_4_23;
	TLabel *eq_4_24;
	TLabel *eq_4_25;
	TLabel *eq_4_26;
	TLabel *eq_4_27;
	TLabel *eq_4_28;
	TLabel *eq_4_29;
	TLabel *eq_4_30;
	TLabel *eq_4_31;
	TLabel *eq_4_32;
	TLabel *eq_4_33;
	TLabel *eq_4_34;
	TLabel *eq_4_35;
	TLabel *eq_4_36;
	TLabel *eq_4_37;
	TLabel *eq_4_38;
	TLabel *eq_4_39;
	TLabel *eq_4_40;
	TLabel *eq_4_41;
	TLabel *eq_4_42;
	TLabel *eq_4_43;
	TLabel *eq_4_44;
	TLabel *eq_4_45;
	TLabel *eq_4_46;
	TLabel *eq_4_47;
	TLabel *eq_4_48;
	TLabel *eq_4_49;
	TLabel *eq_4_50;
	TLabel *eq_4_51;
	TLabel *eq_4_52;
	TLabel *eq_4_53;
	TLabel *eq_4_54;
	TLabel *eq_4_55;
	TLabel *eq_4_56;
	TLabel *eq_4_57;
	TLabel *eq_4_58;
	TLabel *eq_4_59;
	TLabel *eq_4_60;
	TLabel *eq_4_61;
	TLabel *eq_4_62;
	TLabel *eq_4_63;
	TLabel *eq_4_64;
	TLabel *eq_4_65;
	TLabel *eq_4_66;
	TLabel *eq_4_67;
	TLabel *eq_4_68;
	TLabel *eq_4_69;
	TLabel *eq_4_70;
	TLabel *l4_73;
	TLabel *l4_74;
	TLabel *l4_75;
	TLabel *l4_76;
	TLabel *l4_77;
	TLabel *l4_78;
	TLabel *eq_4_71;
	TLabel *eq_4_72;
	TLabel *eq_4_73;
	TLabel *eq_4_74;
	TLabel *eq_4_75;
	TLabel *eq_4_76;
	TLabel *eq_4_77;
	TLabel *eq_4_78;
	TLabel *Label345;
	TTrackBar *TB_4_1;
	TTrackBar *TB_4_2;
	TTrackBar *TB_4_3;
	TTrackBar *TB_4_4;
	TTrackBar *TB_4_5;
	TTrackBar *TB_4_6;
	TTrackBar *TB_4_7;
	TTrackBar *TB_4_8;
	TTrackBar *TB_4_9;
	TTrackBar *TB_4_10;
	TTrackBar *TB_4_11;
	TTrackBar *TB_4_12;
	TTrackBar *TB_4_13;
	TTrackBar *TB_4_14;
	TTrackBar *TB_4_15;
	TTrackBar *TB_4_16;
	TTrackBar *TB_4_17;
	TTrackBar *TB_4_18;
	TTrackBar *TB_4_19;
	TTrackBar *TB_4_20;
	TTrackBar *TB_4_21;
	TTrackBar *TB_4_22;
	TTrackBar *TB_4_23;
	TTrackBar *TB_4_24;
	TTrackBar *TB_4_25;
	TTrackBar *TB_4_26;
	TTrackBar *TB_4_27;
	TTrackBar *TB_4_28;
	TTrackBar *TB_4_29;
	TTrackBar *TB_4_30;
	TTrackBar *TB_4_31;
	TTrackBar *TB_4_32;
	TTrackBar *TB_4_33;
	TTrackBar *TB_4_34;
	TTrackBar *TB_4_35;
	TTrackBar *TB_4_36;
	TTrackBar *TB_4_37;
	TTrackBar *TB_4_38;
	TTrackBar *TB_4_39;
	TTrackBar *TB_4_40;
	TTrackBar *TB_4_41;
	TTrackBar *TB_4_42;
	TTrackBar *TB_4_43;
	TTrackBar *TB_4_44;
	TTrackBar *TB_4_45;
	TTrackBar *TB_4_46;
	TTrackBar *TB_4_47;
	TTrackBar *TB_4_48;
	TTrackBar *TB_4_49;
	TTrackBar *TB_4_50;
	TTrackBar *TB_4_51;
	TTrackBar *TB_4_52;
	TTrackBar *TB_4_53;
	TTrackBar *TB_4_54;
	TTrackBar *TB_4_55;
	TTrackBar *TB_4_56;
	TTrackBar *TB_4_57;
	TTrackBar *TB_4_58;
	TTrackBar *TB_4_59;
	TTrackBar *TB_4_60;
	TTrackBar *TB_4_61;
	TTrackBar *TB_4_62;
	TTrackBar *TB_4_63;
	TTrackBar *TB_4_64;
	TTrackBar *TB_4_65;
	TTrackBar *TB_4_66;
	TTrackBar *TB_4_67;
	TTrackBar *TB_4_68;
	TTrackBar *TB_4_69;
	TTrackBar *TB_4_70;
	TTrackBar *TB_4_71;
	TTrackBar *TB_4_72;
	TTrackBar *TB_4_73;
	TTrackBar *TB_4_74;
	TTrackBar *TB_4_75;
	TTrackBar *TB_4_76;
	TTrackBar *TB_4_77;
	TTrackBar *TB_4_78;
	TButton *Button1;
	TButton *btn_type4_all_up;
	TButton *btn_type4_all_down;
	TButton *btn_type4_copy_from_type3;
	TRadioButton *rdo_type4_value_x1;
	TRadioButton *rdo_type4_value_x2;
	TTrackBar *TB_4_79;
	TLabel *Label189;
	TTrackBar *TB_4_80;
	TLabel *Label190;
	TTrackBar *TB_4_81;
	TTrackBar *TB_4_83;
	TTrackBar *TB_4_82;
	TTrackBar *TB_4_84;
	TTrackBar *TB_4_85;
	TTrackBar *TB_4_86;
	TTrackBar *TB_4_87;
	TTrackBar *TB_4_88;
	TTrackBar *TB_4_89;
	TTrackBar *TB_4_90;
	TLabel *Label191;
	TLabel *Label192;
	TLabel *Label193;
	TLabel *Label194;
	TLabel *Label195;
	TLabel *Label196;
	TLabel *Label197;
	TLabel *Label198;
	TLabel *Label199;
	TLabel *Label200;
	TTrackBar *TB_4_98;
	TTrackBar *TB_4_97;
	TTrackBar *TB_4_96;
	TTrackBar *TB_4_95;
	TTrackBar *TB_4_94;
	TTrackBar *TB_4_93;
	TTrackBar *TB_4_92;
	TTrackBar *TB_4_91;
	TLabel *Label201;
	TLabel *Label202;
	TLabel *Label203;
	TLabel *Label204;
	TLabel *Label205;
	TLabel *Label206;
	TLabel *Label207;
	TLabel *Label208;
	TLabel *eq_4_98;
	TLabel *eq_4_97;
	TLabel *eq_4_96;
	TLabel *eq_4_95;
	TLabel *eq_4_94;
	TLabel *eq_4_93;
	TLabel *eq_4_92;
	TLabel *eq_4_91;
	TLabel *eq_4_90;
	TLabel *eq_4_89;
	TLabel *eq_4_88;
	TLabel *eq_4_87;
	TLabel *eq_4_86;
	TLabel *eq_4_85;
	TLabel *eq_4_84;
	TLabel *eq_4_83;
	TLabel *eq_4_82;
	TLabel *eq_4_81;
	TLabel *eq_4_80;
	TLabel *eq_4_79;
	TComboBox *cmbT1_range_from;
	TLabel *Label209;
	TComboBox *cmbT1_range_to;
	TComboBox *cmbT2_range_from;
	TLabel *Label210;
	TComboBox *cmbT2_range_to;
	TComboBox *cmbT4_range_from;
	TComboBox *cmbT4_range_to;
	TComboBox *cmbT3_range_from;
	TComboBox *cmbT3_range_to;
	TLabel *Label211;
	TLabel *Label213;
	TLabel *T1_range_label;
	TLabel *T2_range_label;
	TLabel *T3_range_label;
	TLabel *T4_range_label;
	TCheckBox *TB_4_1_Cutoff;
	TCheckBox *TB_4_2_Cutoff;
	TCheckBox *TB_4_3_Cutoff;
	TCheckBox *TB_4_4_Cutoff;
	TCheckBox *TB_4_5_Cutoff;
	TCheckBox *TB_4_6_Cutoff;
	TCheckBox *TB_4_7_Cutoff;
	TCheckBox *TB_4_8_Cutoff;
	TCheckBox *TB_4_9_Cutoff;
	TCheckBox *TB_4_10_Cutoff;
	TCheckBox *TB_4_11_Cutoff;
	TCheckBox *TB_4_12_Cutoff;
	TCheckBox *TB_4_13_Cutoff;
	TCheckBox *TB_4_36_Cutoff;
	TCheckBox *TB_4_37_Cutoff;
	TCheckBox *TB_4_38_Cutoff;
	TCheckBox *TB_4_39_Cutoff;
	TCheckBox *TB_4_40_Cutoff;
	TCheckBox *TB_4_41_Cutoff;
	TCheckBox *TB_4_42_Cutoff;
	TCheckBox *TB_4_43_Cutoff;
	TCheckBox *TB_4_44_Cutoff;
	TCheckBox *TB_4_45_Cutoff;
	TCheckBox *TB_4_46_Cutoff;
	TCheckBox *TB_4_47_Cutoff;
	TCheckBox *TB_4_48_Cutoff;
	TCheckBox *TB_4_49_Cutoff;
	TCheckBox *TB_4_50_Cutoff;
	TCheckBox *TB_4_51_Cutoff;
	TCheckBox *TB_4_52_Cutoff;
	TCheckBox *TB_4_53_Cutoff;
	TCheckBox *TB_4_54_Cutoff;
	TCheckBox *TB_4_55_Cutoff;
	TCheckBox *TB_4_56_Cutoff;
	TCheckBox *TB_4_57_Cutoff;
	TCheckBox *TB_4_58_Cutoff;
	TCheckBox *TB_4_59_Cutoff;
	TCheckBox *TB_4_60_Cutoff;
	TCheckBox *TB_4_61_Cutoff;
	TCheckBox *TB_4_62_Cutoff;
	TCheckBox *TB_4_63_Cutoff;
	TCheckBox *TB_4_64_Cutoff;
	TCheckBox *TB_4_65_Cutoff;
	TCheckBox *TB_4_66_Cutoff;
	TCheckBox *TB_4_67_Cutoff;
	TCheckBox *TB_4_68_Cutoff;
	TCheckBox *TB_4_69_Cutoff;
	TCheckBox *TB_4_70_Cutoff;
	TCheckBox *TB_4_71_Cutoff;
	TCheckBox *TB_4_72_Cutoff;
	TCheckBox *TB_4_73_Cutoff;
	TCheckBox *TB_4_74_Cutoff;
	TCheckBox *TB_4_75_Cutoff;
	TCheckBox *TB_4_76_Cutoff;
	TCheckBox *TB_4_77_Cutoff;
	TCheckBox *TB_4_78_Cutoff;
	TCheckBox *TB_4_79_Cutoff;
	TCheckBox *TB_4_80_Cutoff;
	TCheckBox *TB_4_81_Cutoff;
	TCheckBox *TB_4_82_Cutoff;
	TCheckBox *TB_4_83_Cutoff;
	TCheckBox *TB_4_84_Cutoff;
	TCheckBox *TB_4_85_Cutoff;
	TCheckBox *TB_4_86_Cutoff;
	TCheckBox *TB_4_87_Cutoff;
	TCheckBox *TB_4_88_Cutoff;
	TCheckBox *TB_4_89_Cutoff;
	TCheckBox *TB_4_90_Cutoff;
	TCheckBox *TB_4_91_Cutoff;
	TCheckBox *TB_4_92_Cutoff;
	TCheckBox *TB_4_93_Cutoff;
	TCheckBox *TB_4_94_Cutoff;
	TCheckBox *TB_4_95_Cutoff;
	TCheckBox *TB_4_96_Cutoff;
	TCheckBox *TB_4_97_Cutoff;
	TCheckBox *TB_4_98_Cutoff;
	TMemo *Memo1;
	TRadioButton *rdo_file_io_sec;
	TComboBox *cmbFIOSecSize;
	TComboBox *cmbFIOMBSize;
	TRadioButton *rdo_file_io_mb;
	void __fastcall btnExitClick(TObject *Sender);
	void __fastcall btnAddClick(TObject *Sender);
	void __fastcall btnDelClick(TObject *Sender);
	void __fastcall btnUpClick(TObject *Sender);
	void __fastcall btnDownClick(TObject *Sender);
	void __fastcall LvFileSelectItem(TObject *Sender, TListItem *Item, bool Selected);
	void __fastcall btnClearClick(TObject *Sender);
	void __fastcall edtOutputPathLeftButtonClick(TObject *Sender);
	void __fastcall edtOutputPathRightButtonClick(TObject *Sender);
	void __fastcall edtSuffixRightButtonClick(TObject *Sender);
	void __fastcall LvFileChange(TObject *Sender, TListItem *Item, TItemChange Change);
	void __fastcall btnStartClick(TObject *Sender);
	void __fastcall UpdateProgress(int index,AnsiString status,int persent);
	void __fastcall EndExec(int index,DWORD exitCode);
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall FormCloseQuery(TObject *Sender, bool &CanClose);
	void __fastcall btnReloadClick(TObject *Sender);
	void __fastcall btnInfoClick(TObject *Sender);
	void __fastcall btnAbortClick(TObject *Sender);
	void __fastcall chk_change_default_parameterClick(TObject *Sender);
	void __fastcall btnDPClick(TObject *Sender);
	void __fastcall btnPauseClick(TObject *Sender);
	void __fastcall btnSortClick(TObject *Sender);
	void __fastcall LvFileColumnClick(TObject *Sender, TListColumn *Column);
	void __fastcall btnOK_ClearClick(TObject *Sender);
	void __fastcall btn_eq_saveClick(TObject *Sender);
	void __fastcall btn_LoadClick(TObject *Sender);
	void __fastcall TB_1_1Change(TObject *Sender);
	void __fastcall TB_1_2Change(TObject *Sender);
	void __fastcall TB_1_3Change(TObject *Sender);
	void __fastcall TB_1_4Change(TObject *Sender);
	void __fastcall TB_1_5Change(TObject *Sender);
	void __fastcall TB_1_6Change(TObject *Sender);
	void __fastcall TB_1_7Change(TObject *Sender);
	void __fastcall TB_1_8Change(TObject *Sender);
	void __fastcall TB_1_9Change(TObject *Sender);
	void __fastcall TB_1_10Change(TObject *Sender);
	void __fastcall TB_1_11Change(TObject *Sender);
	void __fastcall TB_1_12Change(TObject *Sender);
	void __fastcall TB_1_13Change(TObject *Sender);
	void __fastcall TB_1_14Change(TObject *Sender);
	void __fastcall TB_1_15Change(TObject *Sender);
	void __fastcall TB_1_16Change(TObject *Sender);
	void __fastcall TB_1_17Change(TObject *Sender);
	void __fastcall TB_1_18Change(TObject *Sender);
	void __fastcall TB_1_19Change(TObject *Sender);
	void __fastcall TB_1_20Change(TObject *Sender);
	void __fastcall TB_1_21Change(TObject *Sender);
	void __fastcall TB_1_22Change(TObject *Sender);
	void __fastcall TB_1_23Change(TObject *Sender);
	void __fastcall TB_1_24Change(TObject *Sender);
	void __fastcall TB_1_25Change(TObject *Sender);
	void __fastcall TB_1_26Change(TObject *Sender);
	void __fastcall TB_1_27Change(TObject *Sender);
	void __fastcall TB_1_28Change(TObject *Sender);
	void __fastcall TB_1_29Change(TObject *Sender);
	void __fastcall TB_1_30Change(TObject *Sender);
	void __fastcall TB_1_31Change(TObject *Sender);
	void __fastcall TB_1_32Change(TObject *Sender);
	void __fastcall TB_1_33Change(TObject *Sender);
	void __fastcall TB_1_34Change(TObject *Sender);
	void __fastcall TB_1_35Change(TObject *Sender);
	void __fastcall btn_type1_all_centerClick(TObject *Sender);
	void __fastcall btn_type1_all_upClick(TObject *Sender);
	void __fastcall btn_type1_all_downClick(TObject *Sender);
	void __fastcall TB_2_1Change(TObject *Sender);
	void __fastcall TB_2_2Change(TObject *Sender);
	void __fastcall TB_2_3Change(TObject *Sender);
	void __fastcall TB_2_4Change(TObject *Sender);
	void __fastcall TB_2_5Change(TObject *Sender);
	void __fastcall TB_2_6Change(TObject *Sender);
	void __fastcall TB_2_7Change(TObject *Sender);
	void __fastcall TB_2_8Change(TObject *Sender);
	void __fastcall TB_2_9Change(TObject *Sender);
	void __fastcall TB_2_10Change(TObject *Sender);
	void __fastcall TB_2_11Change(TObject *Sender);
	void __fastcall TB_2_12Change(TObject *Sender);
	void __fastcall TB_2_13Change(TObject *Sender);
	void __fastcall TB_2_14Change(TObject *Sender);
	void __fastcall TB_2_15Change(TObject *Sender);
	void __fastcall TB_2_16Change(TObject *Sender);
	void __fastcall TB_2_17Change(TObject *Sender);
	void __fastcall TB_2_18Change(TObject *Sender);
	void __fastcall TB_2_19Change(TObject *Sender);
	void __fastcall TB_2_20Change(TObject *Sender);
	void __fastcall TB_2_21Change(TObject *Sender);
	void __fastcall TB_2_22Change(TObject *Sender);
	void __fastcall TB_2_23Change(TObject *Sender);
	void __fastcall TB_2_24Change(TObject *Sender);
	void __fastcall TB_2_25Change(TObject *Sender);
	void __fastcall TB_2_26Change(TObject *Sender);
	void __fastcall TB_2_27Change(TObject *Sender);
	void __fastcall TB_2_28Change(TObject *Sender);
	void __fastcall TB_2_29Change(TObject *Sender);
	void __fastcall TB_2_30Change(TObject *Sender);
	void __fastcall TB_2_31Change(TObject *Sender);
	void __fastcall TB_2_32Change(TObject *Sender);
	void __fastcall TB_2_33Change(TObject *Sender);
	void __fastcall TB_2_34Change(TObject *Sender);
	void __fastcall TB_2_35Change(TObject *Sender);
	void __fastcall TB_2_36Change(TObject *Sender);
	void __fastcall TB_2_37Change(TObject *Sender);
	void __fastcall TB_2_38Change(TObject *Sender);
	void __fastcall TB_2_39Change(TObject *Sender);
	void __fastcall TB_2_40Change(TObject *Sender);
	void __fastcall TB_2_41Change(TObject *Sender);
	void __fastcall TB_2_42Change(TObject *Sender);
	void __fastcall TB_2_43Change(TObject *Sender);
	void __fastcall TB_2_44Change(TObject *Sender);
	void __fastcall TB_2_45Change(TObject *Sender);
	void __fastcall TB_2_46Change(TObject *Sender);
	void __fastcall TB_2_47Change(TObject *Sender);
	void __fastcall TB_2_48Change(TObject *Sender);
	void __fastcall TB_2_49Change(TObject *Sender);
	void __fastcall TB_2_50Change(TObject *Sender);
	void __fastcall btn_type2_all_centerClick(TObject *Sender);
	void __fastcall btn_type2_all_upClick(TObject *Sender);
	void __fastcall btn_type2_all_downClick(TObject *Sender);
	void __fastcall TB_3_1Change(TObject *Sender);
	void __fastcall TB_3_2Change(TObject *Sender);
	void __fastcall TB_3_3Change(TObject *Sender);
	void __fastcall TB_3_4Change(TObject *Sender);
	void __fastcall TB_3_5Change(TObject *Sender);
	void __fastcall TB_3_6Change(TObject *Sender);
	void __fastcall TB_3_7Change(TObject *Sender);
	void __fastcall TB_3_8Change(TObject *Sender);
	void __fastcall TB_3_9Change(TObject *Sender);
	void __fastcall TB_3_10Change(TObject *Sender);
	void __fastcall TB_3_11Change(TObject *Sender);
	void __fastcall TB_3_12Change(TObject *Sender);
	void __fastcall TB_3_13Change(TObject *Sender);
	void __fastcall TB_3_14Change(TObject *Sender);
	void __fastcall TB_3_15Change(TObject *Sender);
	void __fastcall TB_3_16Change(TObject *Sender);
	void __fastcall TB_3_17Change(TObject *Sender);
	void __fastcall TB_3_18Change(TObject *Sender);
	void __fastcall TB_3_19Change(TObject *Sender);
	void __fastcall TB_3_20Change(TObject *Sender);
	void __fastcall TB_3_21Change(TObject *Sender);
	void __fastcall TB_3_22Change(TObject *Sender);
	void __fastcall TB_3_23Change(TObject *Sender);
	void __fastcall TB_3_24Change(TObject *Sender);
	void __fastcall TB_3_25Change(TObject *Sender);
	void __fastcall TB_3_26Change(TObject *Sender);
	void __fastcall TB_3_27Change(TObject *Sender);
	void __fastcall TB_3_28Change(TObject *Sender);
	void __fastcall TB_3_29Change(TObject *Sender);
	void __fastcall TB_3_30Change(TObject *Sender);
	void __fastcall TB_3_31Change(TObject *Sender);
	void __fastcall TB_3_32Change(TObject *Sender);
	void __fastcall TB_3_33Change(TObject *Sender);
	void __fastcall TB_3_34Change(TObject *Sender);
	void __fastcall TB_3_35Change(TObject *Sender);
	void __fastcall TB_3_36Change(TObject *Sender);
	void __fastcall TB_3_37Change(TObject *Sender);
	void __fastcall TB_3_38Change(TObject *Sender);
	void __fastcall TB_3_39Change(TObject *Sender);
	void __fastcall TB_3_40Change(TObject *Sender);
	void __fastcall TB_3_41Change(TObject *Sender);
	void __fastcall TB_3_42Change(TObject *Sender);
	void __fastcall TB_3_43Change(TObject *Sender);
	void __fastcall TB_3_44Change(TObject *Sender);
	void __fastcall TB_3_45Change(TObject *Sender);
	void __fastcall TB_3_46Change(TObject *Sender);
	void __fastcall TB_3_47Change(TObject *Sender);
	void __fastcall TB_3_48Change(TObject *Sender);
	void __fastcall TB_3_49Change(TObject *Sender);
	void __fastcall TB_3_50Change(TObject *Sender);
	void __fastcall TB_3_51Change(TObject *Sender);
	void __fastcall TB_3_52Change(TObject *Sender);
	void __fastcall TB_3_53Change(TObject *Sender);
	void __fastcall TB_3_54Change(TObject *Sender);
	void __fastcall TB_3_55Change(TObject *Sender);
	void __fastcall TB_3_56Change(TObject *Sender);
	void __fastcall TB_3_57Change(TObject *Sender);
	void __fastcall TB_3_58Change(TObject *Sender);
	void __fastcall TB_3_59Change(TObject *Sender);
	void __fastcall TB_3_60Change(TObject *Sender);
	void __fastcall TB_3_61Change(TObject *Sender);
	void __fastcall TB_3_62Change(TObject *Sender);
	void __fastcall TB_3_63Change(TObject *Sender);
	void __fastcall TB_3_64Change(TObject *Sender);
	void __fastcall TB_3_65Change(TObject *Sender);
	void __fastcall TB_3_66Change(TObject *Sender);
	void __fastcall TB_3_67Change(TObject *Sender);
	void __fastcall TB_3_68Change(TObject *Sender);
	void __fastcall TB_3_69Change(TObject *Sender);
	void __fastcall TB_3_70Change(TObject *Sender);
	void __fastcall TB_3_71Change(TObject *Sender);
	void __fastcall TB_3_72Change(TObject *Sender);
	void __fastcall TB_3_73Change(TObject *Sender);
	void __fastcall TB_3_74Change(TObject *Sender);
	void __fastcall TB_3_75Change(TObject *Sender);
	void __fastcall TB_3_76Change(TObject *Sender);
	void __fastcall TB_3_77Change(TObject *Sender);
	void __fastcall TB_3_78Change(TObject *Sender);
	void __fastcall btn_type3_all_centerClick(TObject *Sender);
	void __fastcall btn_type3_all_upClick(TObject *Sender);
	void __fastcall btn_type3_all_downClick(TObject *Sender);
	void __fastcall btn_type2_copy_from_type1Click(TObject *Sender);
	void __fastcall btnPreviewAppClick(TObject *Sender);
	void __fastcall btn_type3_copy_from_type2Click(TObject *Sender);
	void __fastcall edt_eq_titleChange(TObject *Sender);
	void __fastcall btn_eq_deleteClick(TObject *Sender);
	void __fastcall track_skip_positionChange(TObject *Sender);
	void __fastcall btnPlayClick(TObject *Sender);
	void __fastcall btn_ana_addClick(TObject *Sender);
	void __fastcall btnAnaDelClick(TObject *Sender);
	void __fastcall btnAnaClearClick(TObject *Sender);
	void __fastcall btnAnaUpClick(TObject *Sender);
	void __fastcall btnAnaDownClick(TObject *Sender);
	void __fastcall pageMainChange(TObject *Sender);
	void __fastcall LvAnaFileSelectItem(TObject *Sender, TListItem *Item, bool Selected);
	void __fastcall Timer1Timer(TObject *Sender);
	void __fastcall Timer2Timer(TObject *Sender);
	void __fastcall cmbEQParameterChange(TObject *Sender);
	void __fastcall cmbEQ_AnalyzeChange(TObject *Sender);
	void __fastcall LvAnaFileChange(TObject *Sender, TListItem *Item, TItemChange Change);
	void __fastcall rdo_Analyze_Phase2Click(TObject *Sender);
	void __fastcall rdo_Analyze_Phase3Click(TObject *Sender);
	void __fastcall rdo_Analyze_Phase1Click(TObject *Sender);
	void __fastcall btn_EQ_SetClick(TObject *Sender);
	void __fastcall cmbPlayDeviceChange(TObject *Sender);
	void __fastcall cmb_preview_lengthChange(TObject *Sender);
	void __fastcall CategoryPanel1Expand(TObject *Sender);
	void __fastcall CategoryPanel2Expand(TObject *Sender);
	void __fastcall rdo_log_disableClick(TObject *Sender);
	void __fastcall rdo_log_enableClick(TObject *Sender);
	void __fastcall be_logLeftButtonClick(TObject *Sender);
	void __fastcall be_logRightButtonClick(TObject *Sender);
	void __fastcall Timer3Timer(TObject *Sender);
	void __fastcall Timer4Timer(TObject *Sender);
	void __fastcall rdo_window_size1Click(TObject *Sender);
	void __fastcall rdo_window_size2Click(TObject *Sender);
	void __fastcall rdo_window_size3Click(TObject *Sender);
	void __fastcall cmbNormalizeChange(TObject *Sender);
	void __fastcall TB_4_1Change(TObject *Sender);
	void __fastcall TB_4_2Change(TObject *Sender);
	void __fastcall TB_4_3Change(TObject *Sender);
	void __fastcall TB_4_4Change(TObject *Sender);
	void __fastcall TB_4_5Change(TObject *Sender);
	void __fastcall TB_4_6Change(TObject *Sender);
	void __fastcall TB_4_7Change(TObject *Sender);
	void __fastcall TB_4_8Change(TObject *Sender);
	void __fastcall TB_4_9Change(TObject *Sender);
	void __fastcall TB_4_10Change(TObject *Sender);
	void __fastcall TB_4_11Change(TObject *Sender);
	void __fastcall TB_4_12Change(TObject *Sender);
	void __fastcall TB_4_13Change(TObject *Sender);
	void __fastcall TB_4_14Change(TObject *Sender);
	void __fastcall TB_4_15Change(TObject *Sender);
	void __fastcall TB_4_16Change(TObject *Sender);
	void __fastcall TB_4_17Change(TObject *Sender);
	void __fastcall TB_4_18Change(TObject *Sender);
	void __fastcall TB_4_19Change(TObject *Sender);
	void __fastcall TB_4_20Change(TObject *Sender);
	void __fastcall TB_4_21Change(TObject *Sender);
	void __fastcall TB_4_22Change(TObject *Sender);
	void __fastcall TB_4_23Change(TObject *Sender);
	void __fastcall TB_4_24Change(TObject *Sender);
	void __fastcall TB_4_25Change(TObject *Sender);
	void __fastcall TB_4_26Change(TObject *Sender);
	void __fastcall TB_4_27Change(TObject *Sender);
	void __fastcall TB_4_28Change(TObject *Sender);
	void __fastcall TB_4_29Change(TObject *Sender);
	void __fastcall TB_4_30Change(TObject *Sender);
	void __fastcall TB_4_31Change(TObject *Sender);
	void __fastcall TB_4_32Change(TObject *Sender);
	void __fastcall TB_4_33Change(TObject *Sender);
	void __fastcall TB_4_34Change(TObject *Sender);
	void __fastcall TB_4_35Change(TObject *Sender);
	void __fastcall TB_4_36Change(TObject *Sender);
	void __fastcall TB_4_37Change(TObject *Sender);
	void __fastcall TB_4_38Change(TObject *Sender);
	void __fastcall TB_4_39Change(TObject *Sender);
	void __fastcall TB_4_40Change(TObject *Sender);
	void __fastcall TB_4_41Change(TObject *Sender);
	void __fastcall TB_4_42Change(TObject *Sender);
	void __fastcall TB_4_43Change(TObject *Sender);
	void __fastcall TB_4_44Change(TObject *Sender);
	void __fastcall TB_4_45Change(TObject *Sender);
	void __fastcall TB_4_46Change(TObject *Sender);
	void __fastcall TB_4_47Change(TObject *Sender);
	void __fastcall TB_4_48Change(TObject *Sender);
	void __fastcall TB_4_49Change(TObject *Sender);
	void __fastcall TB_4_50Change(TObject *Sender);
	void __fastcall TB_4_51Change(TObject *Sender);
	void __fastcall TB_4_52Change(TObject *Sender);
	void __fastcall TB_4_53Change(TObject *Sender);
	void __fastcall TB_4_54Change(TObject *Sender);
	void __fastcall TB_4_55Change(TObject *Sender);
	void __fastcall TB_4_56Change(TObject *Sender);
	void __fastcall TB_4_57Change(TObject *Sender);
	void __fastcall TB_4_58Change(TObject *Sender);
	void __fastcall TB_4_59Change(TObject *Sender);
	void __fastcall TB_4_60Change(TObject *Sender);
	void __fastcall TB_4_61Change(TObject *Sender);
	void __fastcall TB_4_62Change(TObject *Sender);
	void __fastcall TB_4_63Change(TObject *Sender);
	void __fastcall TB_4_64Change(TObject *Sender);
	void __fastcall TB_4_65Change(TObject *Sender);
	void __fastcall TB_4_66Change(TObject *Sender);
	void __fastcall TB_4_67Change(TObject *Sender);
	void __fastcall TB_4_68Change(TObject *Sender);
	void __fastcall TB_4_69Change(TObject *Sender);
	void __fastcall TB_4_70Change(TObject *Sender);
	void __fastcall TB_4_71Change(TObject *Sender);
	void __fastcall TB_4_72Change(TObject *Sender);
	void __fastcall TB_4_73Change(TObject *Sender);
	void __fastcall TB_4_74Change(TObject *Sender);
	void __fastcall TB_4_75Change(TObject *Sender);
	void __fastcall TB_4_76Change(TObject *Sender);
	void __fastcall TB_4_77Change(TObject *Sender);
	void __fastcall TB_4_78Change(TObject *Sender);
	void __fastcall TB_4_79Change(TObject *Sender);
	void __fastcall TB_4_80Change(TObject *Sender);
	void __fastcall TB_4_81Change(TObject *Sender);
	void __fastcall TB_4_82Change(TObject *Sender);
	void __fastcall TB_4_83Change(TObject *Sender);
	void __fastcall TB_4_84Change(TObject *Sender);
	void __fastcall TB_4_85Change(TObject *Sender);
	void __fastcall TB_4_86Change(TObject *Sender);
	void __fastcall TB_4_87Change(TObject *Sender);
	void __fastcall TB_4_88Change(TObject *Sender);
	void __fastcall TB_4_89Change(TObject *Sender);
	void __fastcall TB_4_90Change(TObject *Sender);
	void __fastcall TB_4_91Change(TObject *Sender);
	void __fastcall TB_4_92Change(TObject *Sender);
	void __fastcall TB_4_93Change(TObject *Sender);
	void __fastcall TB_4_94Change(TObject *Sender);
	void __fastcall TB_4_95Change(TObject *Sender);
	void __fastcall TB_4_96Change(TObject *Sender);
	void __fastcall TB_4_97Change(TObject *Sender);
	void __fastcall TB_4_98Change(TObject *Sender);
	void __fastcall Button1Click(TObject *Sender);
	void __fastcall btn_type4_all_upClick(TObject *Sender);
	void __fastcall btn_type4_all_downClick(TObject *Sender);
	void __fastcall btn_type4_copy_from_type3Click(TObject *Sender);
	void __fastcall cmbT1_range_fromChange(TObject *Sender);
	void __fastcall cmbT1_range_toChange(TObject *Sender);
	void __fastcall cmbT2_range_fromChange(TObject *Sender);
	void __fastcall cmbT2_range_toChange(TObject *Sender);
	void __fastcall cmbT3_range_fromChange(TObject *Sender);
	void __fastcall cmbT3_range_toChange(TObject *Sender);
	void __fastcall cmbT4_range_fromChange(TObject *Sender);
	void __fastcall cmbT4_range_toChange(TObject *Sender);
	void __fastcall TB_4_1_CutoffClick(TObject *Sender);
	void __fastcall TB_4_2_CutoffClick(TObject *Sender);
	void __fastcall TB_4_3_CutoffClick(TObject *Sender);
	void __fastcall TB_4_4_CutoffClick(TObject *Sender);
	void __fastcall TB_4_5_CutoffClick(TObject *Sender);
	void __fastcall TB_4_6_CutoffClick(TObject *Sender);
	void __fastcall TB_4_7_CutoffClick(TObject *Sender);
	void __fastcall TB_4_8_CutoffClick(TObject *Sender);
	void __fastcall TB_4_9_CutoffClick(TObject *Sender);
	void __fastcall TB_4_10_CutoffClick(TObject *Sender);
	void __fastcall TB_4_11_CutoffClick(TObject *Sender);
	void __fastcall TB_4_12_CutoffClick(TObject *Sender);
	void __fastcall TB_4_13_CutoffClick(TObject *Sender);
	void __fastcall TB_4_36_CutoffClick(TObject *Sender);
	void __fastcall TB_4_37_CutoffClick(TObject *Sender);
	void __fastcall TB_4_38_CutoffClick(TObject *Sender);
	void __fastcall TB_4_39_CutoffClick(TObject *Sender);
	void __fastcall TB_4_40_CutoffClick(TObject *Sender);
	void __fastcall TB_4_41_CutoffClick(TObject *Sender);
	void __fastcall TB_4_42_CutoffClick(TObject *Sender);
	void __fastcall TB_4_43_CutoffClick(TObject *Sender);
	void __fastcall TB_4_44_CutoffClick(TObject *Sender);
	void __fastcall TB_4_45_CutoffClick(TObject *Sender);
	void __fastcall TB_4_46_CutoffClick(TObject *Sender);
	void __fastcall TB_4_47_CutoffClick(TObject *Sender);
	void __fastcall TB_4_48_CutoffClick(TObject *Sender);
	void __fastcall TB_4_49_CutoffClick(TObject *Sender);
	void __fastcall TB_4_50_CutoffClick(TObject *Sender);
	void __fastcall TB_4_51_CutoffClick(TObject *Sender);
	void __fastcall TB_4_52_CutoffClick(TObject *Sender);
	void __fastcall TB_4_53_CutoffClick(TObject *Sender);
	void __fastcall TB_4_54_CutoffClick(TObject *Sender);
	void __fastcall TB_4_55_CutoffClick(TObject *Sender);
	void __fastcall TB_4_56_CutoffClick(TObject *Sender);
	void __fastcall TB_4_57_CutoffClick(TObject *Sender);
	void __fastcall TB_4_58_CutoffClick(TObject *Sender);
	void __fastcall TB_4_59_CutoffClick(TObject *Sender);
	void __fastcall TB_4_60_CutoffClick(TObject *Sender);
	void __fastcall TB_4_61_CutoffClick(TObject *Sender);
	void __fastcall TB_4_62_CutoffClick(TObject *Sender);
	void __fastcall TB_4_63_CutoffClick(TObject *Sender);
	void __fastcall TB_4_64_CutoffClick(TObject *Sender);
	void __fastcall TB_4_65_CutoffClick(TObject *Sender);
	void __fastcall TB_4_66_CutoffClick(TObject *Sender);
	void __fastcall TB_4_67_CutoffClick(TObject *Sender);
	void __fastcall TB_4_68_CutoffClick(TObject *Sender);
	void __fastcall TB_4_69_CutoffClick(TObject *Sender);
	void __fastcall TB_4_70_CutoffClick(TObject *Sender);
	void __fastcall TB_4_71_CutoffClick(TObject *Sender);
	void __fastcall TB_4_72_CutoffClick(TObject *Sender);
	void __fastcall TB_4_73_CutoffClick(TObject *Sender);
	void __fastcall TB_4_74_CutoffClick(TObject *Sender);
	void __fastcall TB_4_75_CutoffClick(TObject *Sender);
	void __fastcall TB_4_76_CutoffClick(TObject *Sender);
	void __fastcall TB_4_77_CutoffClick(TObject *Sender);
	void __fastcall TB_4_78_CutoffClick(TObject *Sender);
	void __fastcall TB_4_79_CutoffClick(TObject *Sender);
	void __fastcall TB_4_80_CutoffClick(TObject *Sender);
	void __fastcall TB_4_81_CutoffClick(TObject *Sender);
	void __fastcall TB_4_82_CutoffClick(TObject *Sender);
	void __fastcall TB_4_83_CutoffClick(TObject *Sender);
	void __fastcall TB_4_84_CutoffClick(TObject *Sender);
	void __fastcall TB_4_85_CutoffClick(TObject *Sender);
	void __fastcall TB_4_86_CutoffClick(TObject *Sender);
	void __fastcall TB_4_87_CutoffClick(TObject *Sender);
	void __fastcall TB_4_88_CutoffClick(TObject *Sender);
	void __fastcall TB_4_89_CutoffClick(TObject *Sender);
	void __fastcall TB_4_90_CutoffClick(TObject *Sender);
	void __fastcall TB_4_91_CutoffClick(TObject *Sender);
	void __fastcall TB_4_92_CutoffClick(TObject *Sender);
	void __fastcall TB_4_93_CutoffClick(TObject *Sender);
	void __fastcall TB_4_94_CutoffClick(TObject *Sender);
	void __fastcall TB_4_95_CutoffClick(TObject *Sender);
	void __fastcall TB_4_96_CutoffClick(TObject *Sender);
	void __fastcall TB_4_97_CutoffClick(TObject *Sender);
	void __fastcall TB_4_98_CutoffClick(TObject *Sender);


	private:	// ユーザー宣言
	TWndMethod	orgLvFileWinProc;
	TWndMethod	orgLvAnaFileWinProc;
	Exec_c* threadExec[1];
	int cdp_num[256];
	int cdp_num_max;
	int Abort;
	int VisibleIndex;
	int CoDefParamIndex;
	double *eq_val[1000];
	double eq[400000];
	WAVEFORMATEX Wfe;
	HWAVEOUT WaveOut;
	UINT	 DeviceID[4];
	SOUNDFMT InFmt;
	FILEINFO FileInfo;
	SSIZE    FilenSample;
	SOUND_BUFFER SoundBuffer[16];
	AnsiString preview_input_filename;
	int		 preview_input_filename_state_change;
	int      preview_err_remain;
	int		 CountSoundBuffer;
	int		 IndexSoundBuffer;
	int      IndexPlayBuffer;
	int		 AnalyzePhase;
	int		 SelectFileIndex;
	int		 BeforeRateConv;

	void __fastcall AddToFileList(UnicodeString filename);
	void __fastcall AddToAnaFileList(UnicodeString filename);
	int __fastcall ExecChildProcess(int index,int play_flag);
	int __fastcall CheckModifyEQ();
	void __fastcall SetPositionToTag();
	void __fastcall LvFileWinProc(TMessage& Msg);
	void __fastcall LvAnaFileWinProc(TMessage& Msg);
	UnicodeString __fastcall GetFilePath(int type,wchar_t *data);
	void __fastcall LoadPresetParameter(void);
	void __fastcall ReloadDefaultParameter(int index, int use_index);
	double __fastcall spline(PT2D *pt,int n,double x1,double *h, double *b, double *d, double *g, double *u, double *r);
	double __fastcall lag_interp(PT2D *pt,int n,double x);
	void __fastcall SaveEQ_Type1(int test);
	void __fastcall SaveEQ_Type2(int test);
	void __fastcall SaveEQ_Type3(int test);
	void __fastcall SaveEQ_Type4(int test);
	void __fastcall EQ_AutoSetType1(void);
	void __fastcall EQ_AutoSetType2(void);
	void __fastcall EQ_AutoSetType3(void);
	void __fastcall SaveEQ(void);
	void __fastcall InitSound(void);
	void __fastcall ReadBuffer(int sb_index,int *buffer_ready_flag);
	void __fastcall PlaySound(void);
	void __fastcall StopSound(void);
	void __fastcall Timer1Func(void);
	void __fastcall Timer1AnaFunc(void);
	void __fastcall Timer2Func(void);
	void __fastcall Timer2AnaFunc(void);
	void __fastcall MmWomOpen(TMessage &Message);
	void __fastcall MmWomClose(TMessage &Message);
	void __fastcall MmWomDone(TMessage &Message);
	BEGIN_MESSAGE_MAP
		VCL_MESSAGE_HANDLER(MM_WOM_OPEN, TMessage, MmWomOpen);
		VCL_MESSAGE_HANDLER(MM_WOM_CLOSE, TMessage, MmWomClose);
		VCL_MESSAGE_HANDLER(MM_WOM_DONE, TMessage, MmWomDone);
	END_MESSAGE_MAP(TControl)
public:		// ユーザー宣言
	UnicodeString eqParameterPath;
	__fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
