//---------------------------------------------------------------------------

#ifndef Unit1H
#define Unit1H
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <Vcl.Controls.hpp>
#include <Vcl.StdCtrls.hpp>
#include <Vcl.Forms.hpp>
#include <Vcl.ComCtrls.hpp>
#include <Vcl.ExtCtrls.hpp>
#include <Vcl.Buttons.hpp>
#include <Vcl.ImgList.hpp>
#include <shlobj.h>
#include <FileCtrl.hpp>

#define WM_RESET_DP (1)
#define WM_RELOAD_DP (2)

//---------------------------------------------------------------------------
class TForm1 : public TForm
{
__published:	// IDE で管理されるコンポーネント
	TPageControl *PageControl1;
	TTabSheet *TabSheet1;
	TTabSheet *TabSheet2;
	TComboBox *cmbDefaultParameter;
	TEdit *edtTitle;
	TButton *btnSave;
	TButton *btnLoad;
	TTabSheet *TabSheet3;
	TCategoryPanelGroup *CategoryPanelGroup1;
	TCategoryPanel *CategoryPanel1;
	TLabel *Label1;
	TCheckBox *chkABE;
	TCheckBox *chkPostABE;
	TCheckBox *chkCutHighPassDither;
	TCheckBox *chkLowAdjust;
	TCheckBox *chkHFC_Auto;
	TComboBox *cmbOverSamp;
	TLabel *Label2;
	TLabel *Label3;
	TCheckBox *chkNREnable;
	TEdit *edtNR_Freq;
	TLabel *Label5;
	TEdit *edtNR_Level;
	TUpDown *upD_NR_Level;
	TBevel *Bevel3;
	TCategoryPanel *CategoryPanel2;
	TLabel *Label8;
	TRadioButton *rdoDeE2;
	TRadioButton *rdoDeE3;
	TEdit *edtHFC;
	TEdit *edtLFC;
	TCheckBox *chkEnableHFC;
	TCheckBox *chkEnableLFC;
	TBevel *Bevel5;
	TRadioButton *rdoDeE1;
	TCategoryPanel *CategoryPanel3;
	TLabel *Label15;
	TCheckBox *chkABE_CutLowLevel;
	TCheckBox *chkSmoothingLowLevel;
	TLabel *Label16;
	TEdit *edtABE_CutDitherLv;
	TUpDown *UpD_ABE_CutDitherLv;
	TCategoryPanel *CategoryPanel4;
	TLabel *Label25;
	TButton *btnDelete;
	TCategoryPanelGroup *CategoryPanelGroup2;
	TCategoryPanel *CategoryPanel5;
	TLabel *Label26;
	TCheckBox *chkMC_Center;
	TBevel *Bevel1;
	TLabel *Label27;
	TCheckBox *chkMC_Surround;
	TBevel *Bevel7;
	TLabel *Label28;
	TCheckBox *chkMC_LFE;
	TLabel *Label29;
	TBevel *Bevel8;
	TCheckBox *chkMC_Mono;
	TCheckBox *chkMC_DownMix;
	TCheckBox *chkMC_EchoEffect;
	TEdit *edtMCEchoEffect;
	TUpDown *UpDMC_EchoEffect;
	TBitBtn *btnExit;
	TCategoryPanelGroup *CategoryPanelGroup3;
	TCategoryPanel *CategoryPanel6;
	TButtonedEdit *edtWorkPath;
	TLabel *Label30;
	TImageList *ImageList1;
	TMemo *edtHFA_Preset;
	TTabSheet *TabSheet4;
	TCategoryPanelGroup *CategoryPanelGroup4;
	TCategoryPanel *CategoryPanel7;
	TCheckBox *chkConvOptionOverWrite;
	TLabel *Label32;
	TGroupBox *GroupBox1;
	TComboBox *cmbSamplingOverWrite;
	TGroupBox *GroupBox2;
	TComboBox *cmbBitWidthOverWrite;
	TBevel *Bevel10;
	TBevel *Bevel11;
	TGroupBox *GroupBox3;
	TComboBox *cmbHFA;
	TCheckBox *chkNormalizeOverWrite;
	TGroupBox *GroupBox4;
	TComboBox *cmbNormalize;
	TBevel *Bevel12;
	TLabel *Label31;
	TCheckBox *chkSuffix;
	TButtonedEdit *edtSuffix;
	TCheckBox *chkHFC_OverWrite;
	TBevel *Bevel13;
	TRadioButton *rdoHFA3_0774;
	TLabel *Label33;
	TRadioButton *rdoHFA3_082;
	TBevel *Bevel14;
	TLabel *Label34;
	TRadioButton *rdoABE_0774;
	TRadioButton *rdoABE_080;
	TBevel *Bevel15;
	TCheckBox *chkABE_DeClip;
	TComboBox *cmbHFC_AutoAdjust;
	TLabel *Label36;
	TCheckBox *chkAdFilter;
	TLabel *Label37;
	TLabel *Label39;
	TCheckBox *chkClickNoiseReduction;
	TEdit *edtCLLD_Level;
	TUpDown *UpD_CLLD_Level;
	TLabel *Label38;
	TLabel *Label45;
	TComboBox *cmbVolumeLevelAdjust;
	TLabel *Label46;
	TLabel *Label47;
	TTrackBar *track_hfa3_ala;
	TLabel *lbl_hfa3_ala;
	TLabel *Label48;
	TCheckBox *chkPostNR;
	TButton *btn_folder_open;
	TComboBox *cmbOutputDither;
	TLabel *Label7;
	TEdit *edtOutDitherLv;
	TUpDown *UpD_OutLv;
	TLabel *Label6;
	TBevel *Bevel2;
	TCheckBox *chk_ms_process;
	TRadioButton *rdoHFA3_084;
	TCategoryPanel *CategoryPanel8;
	TComboBox *cmbMidSide;
	TLabel *Label4;
	TRadioButton *rdoABE_086;
	TCheckBox *chk_LRC_process;
	TMemo *Memo1;
	TComboBox *cmb_MS_LRC;
	TMemo *edtParameter;
	TMemo *edtPTitle;
	TCategoryPanel *CategoryPanel10;
	TLabel *Label9;
	TLabel *Label10;
	TButtonedEdit *edtEncorder_FLAC;
	TLabel *Label11;
	TButtonedEdit *edtEncorder_WavPack;
	TLabel *Label12;
	TButtonedEdit *edtEncorder_MP3;
	TLabel *Label44;
	TButtonedEdit *edtEncorder_OPUS;
	TLabel *Label35;
	TButtonedEdit *edtEncorder_M4A;
	TBevel *Bevel9;
	TBevel *Bevel4;
	TLabel *Label50;
	TLabel *Label51;
	TComboBox *cmbEncoderCustom;
	TButtonedEdit *edtEncoderCustomTitle;
	TEdit *edtEncoderCustomParam;
	TButton *btnEncoderCustomSave;
	TButton *btnEncoderCustomDelete;
	TComboBox *cmbEncoderCustomPg;
	TLabel *Label67;
	TLabel *Label68;
	TComboBox *cmbEncoderCustomExt;
	TLabel *Label69;
	TBevel *Bevel16;
	TLabel *Label70;
	TComboBox *cmbHFA3_FFT_Window_Size;
	TLabel *Label71;
	TComboBox *cmbHFA3_FFT_Window_Lvl;
	TLabel *Label72;
	TMemo *edtParameter2;
	TRadioButton *rdoABE_10x;
	TBevel *Bevel19;
	TLabel *Label73;
	TLabel *Label76;
	TEdit *edtCutLevel;
	TUpDown *UpD_CutLevel;
	TComboBox *cmbCutMode;
	TLabel *Label77;
	TLabel *Label13;
	TMemo *memo_eq_title;
	TCheckBox *chkPreEQ;
	TCheckBox *chkPostEQ;
	TComboBox *cmbPreEQ;
	TComboBox *cmbPostEQ;
	TEdit *edt_PreEQ_Title;
	TEdit *edt_PostEQ_Title;
	TScrollBox *ScrollBox1;
	TLabel *Label54;
	TLabel *Label52;
	TComboBox *cmb_HFA3_Freq_Start;
	TLabel *Label53;
	TComboBox *cmb_HFA3_Freq_Len;
	TLabel *Label14;
	TEdit *edt_hfa3_ana_step;
	TUpDown *upd_hfa3_ana_step;
	TLabel *Label55;
	TEdit *edtHFA_LevelAdjWidth;
	TUpDown *upd_hfa_level_adj_width;
	TLabel *Label56;
	TEdit *edtHFA_LevelAdjNX;
	TUpDown *upd_hfa_level_adj_nx;
	TGroupBox *GroupBox5;
	TRadioButton *rdo_ana_step_1;
	TRadioButton *rdo_ana_step_2;
	TRadioButton *rdo_ana_step_3;
	TRadioButton *rdo_ana_step_4;
	TGroupBox *GroupBox7;
	TRadioButton *rdo_level_width_1;
	TRadioButton *rdo_level_width_2;
	TGroupBox *GroupBox8;
	TRadioButton *rdo_level_nx_1;
	TRadioButton *rdo_level_nx_2;
	TRadioButton *rdo_level_nx_3;
	TRadioGroup *RadioGroup1;
	TRadioButton *rdo_hfa3_pp_1;
	TRadioButton *rdo_hfa3_pp_2;
	TRadioButton *rdo_hfa3_pp_3;
	TGroupBox *GroupBox9;
	TLabel *Label57;
	TLabel *lbl_hfa3_sig_level_limit;
	TTrackBar *tb_hfa3_sig_level_limit;
	TLabel *Label58;
	TLabel *Label59;
	TComboBox *cmb_HFA3_Freq_Start_LRC;
	TLabel *Label60;
	TComboBox *cmb_HFA3_Freq_Len_LRC;
	TLabel *Label61;
	TEdit *edt_hfa3_ana_step_LRC;
	TUpDown *upd_hfa3_ana_step_LRC;
	TGroupBox *GroupBox6;
	TRadioButton *rdo_ana_step_1_LRC;
	TRadioButton *rdo_ana_step_2_LRC;
	TRadioButton *rdo_ana_step_3_LRC;
	TRadioButton *rdo_ana_step_4_LRC;
	TLabel *Label62;
	TEdit *edtHFA_LevelAdjWidth_LRC;
	TUpDown *upd_hfa_level_adj_width_LRC;
	TGroupBox *GroupBox10;
	TRadioButton *rdo_level_width_1_LRC;
	TRadioButton *rdo_level_width_2_LRC;
	TLabel *Label63;
	TEdit *edtHFA_LevelAdjNX_LRC;
	TUpDown *upd_hfa_level_adj_nx_LRC;
	TGroupBox *GroupBox11;
	TRadioButton *rdo_level_nx_1_LRC;
	TRadioButton *rdo_level_nx_2_LRC;
	TRadioButton *rdo_level_nx_3_LRC;
	TRadioGroup *RadioGroup2;
	TBevel *Bevel18;
	TRadioButton *rdo_hfa3_pp_1_LRC;
	TRadioButton *rdo_hfa3_pp_2_LRC;
	TRadioButton *rdo_hfa3_pp_3_LRC;
	TGroupBox *GroupBox12;
	TLabel *Label64;
	TLabel *lbl_hfa3_sig_level_limit_LRC;
	TTrackBar *tb_hfa3_sig_level_limit_LRC;
	TGroupBox *GroupBox13;
	TLabel *Label65;
	TLabel *Label66;
	TLabel *Label75;
	TComboBox *cmb_LRC_CC_Phase;
	TComboBox *cmb_LRC_CC_Level;
	TCheckBox *chkEnableCenterHFC;
	TEdit *edtCenterHFC;
	TScrollBox *ScrollBox2;
	TLabel *Label17;
	TComboBox *cmbHFA_Preset;
	TLabel *Label18;
	TEdit *edtHFA_PresetTitle;
	TButton *btnHFA_PresetSave;
	TCheckBox *chkHFA_Sig1_Enable;
	TLabel *Label19;
	TEdit *edtHFA_Sig1_LineX;
	TUpDown *UpD_HFASig1_LineX;
	TLabel *Label20;
	TEdit *edtHFA_Sig1_Phase;
	TUpDown *UpD_HFA_Sig1Phase;
	TCheckBox *chkHFA_Sig2_Enable;
	TLabel *Label21;
	TEdit *edtHFA_Sig2_Phase;
	TUpDown *UpD_HFA_Sig2Phase;
	TCheckBox *chkHFA_Sig3_Enable;
	TLabel *Label22;
	TEdit *edtHFA_Sig3_Phase;
	TUpDown *UpD_HFA_Sig3Phase;
	TLabel *Label23;
	TEdit *edtHFA_NoiseBlendLv;
	TUpDown *UpDHFA_NoiseBlend;
	TLabel *Label49;
	TComboBox *cmbHFA_Level;
	TBevel *Bevel6;
	TLabel *Label24;
	TLabel *Label43;
	TEdit *edtHFA_Filter1;
	TUpDown *UpDHFA_filter1;
	TLabel *Label40;
	TEdit *edtHFA_Filter2;
	TUpDown *UpDHFA_filter2;
	TLabel *Label41;
	TEdit *edtHFA_Filter3;
	TUpDown *UpDHFA_filter3;
	TLabel *Label42;
	TEdit *edtHFA_Filter4;
	TUpDown *UpDHFA_filter4;
	TLabel *Label74;
	void __fastcall CategoryPanel1Expand(TObject *Sender);
	void __fastcall CategoryPanel2Expand(TObject *Sender);
	void __fastcall CategoryPanel3Expand(TObject *Sender);
	void __fastcall CategoryPanel4Expand(TObject *Sender);
	void __fastcall CategoryPanel1Collapse(TObject *Sender);
	void __fastcall CategoryPanel2Collapse(TObject *Sender);
	void __fastcall CategoryPanel3Collapse(TObject *Sender);
	void __fastcall CategoryPanel4Collapse(TObject *Sender);
	void __fastcall CategoryPanel5Collapse(TObject *Sender);
	void __fastcall CategoryPanel6Collapse(TObject *Sender);
	void __fastcall btnExitClick(TObject *Sender);
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall btnLoadClick(TObject *Sender);
	void __fastcall cmbHFA_PresetChange(TObject *Sender);
	void __fastcall btnHFA_PresetSaveClick(TObject *Sender);
	void __fastcall FormCloseQuery(TObject *Sender, bool &CanClose);
	void __fastcall btnSaveClick(TObject *Sender);
	void __fastcall edtWorkPathLeftButtonClick(TObject *Sender);
	void __fastcall edtWorkPathRightButtonClick(TObject *Sender);
	void __fastcall cmbDefaultParameterChange(TObject *Sender);
	void __fastcall btnDeleteClick(TObject *Sender);
	void __fastcall edtTitleKeyPress(TObject *Sender, System::WideChar &Key);
	void __fastcall edtEncorder_FLACKeyPress(TObject *Sender, System::WideChar &Key);
	void __fastcall edtEncorder_WavPackKeyPress(TObject *Sender, System::WideChar &Key);
	void __fastcall edtEncorder_MP3KeyPress(TObject *Sender, System::WideChar &Key);
	void __fastcall edtSuffixKeyPress(TObject *Sender, System::WideChar &Key);
	void __fastcall edtSuffixRightButtonClick(TObject *Sender);
	void __fastcall rdoHFA3_0774Click(TObject *Sender);
	void __fastcall rdoHFA3_082Click(TObject *Sender);
	void __fastcall rdoABE_0774Click(TObject *Sender);
	void __fastcall rdoABE_080Click(TObject *Sender);
	void __fastcall track_hfa3_alaChange(TObject *Sender);
	void __fastcall btn_folder_openClick(TObject *Sender);
	void __fastcall CategoryPanel8Expand(TObject *Sender);
	void __fastcall rdo_ana_step_2Click(TObject *Sender);
	void __fastcall rdo_ana_step_3Click(TObject *Sender);
	void __fastcall rdoHFA3_084Click(TObject *Sender);
	void __fastcall rdo_level_width_1Click(TObject *Sender);
	void __fastcall rdo_level_width_2Click(TObject *Sender);
	void __fastcall rdo_level_nx_1Click(TObject *Sender);
	void __fastcall rdo_level_nx_2Click(TObject *Sender);
	void __fastcall tb_hfa3_sig_level_limitChange(TObject *Sender);
	void __fastcall cmbPreEQChange(TObject *Sender);
	void __fastcall cmbPostEQChange(TObject *Sender);
	void __fastcall rdo_ana_step_2_LRCClick(TObject *Sender);
	void __fastcall rdo_ana_step_3_LRCClick(TObject *Sender);
	void __fastcall rdo_level_width_1_LRCClick(TObject *Sender);
	void __fastcall rdo_level_width_2_LRCClick(TObject *Sender);
	void __fastcall rdo_level_nx_1_LRCClick(TObject *Sender);
	void __fastcall rdo_level_nx_2_LRCClick(TObject *Sender);
	void __fastcall tb_hfa3_sig_level_limit_LRCChange(TObject *Sender);
	void __fastcall CategoryPanel9Expand(TObject *Sender);
	void __fastcall rdo_ana_step_1Click(TObject *Sender);
	void __fastcall rdo_ana_step_1_LRCClick(TObject *Sender);
	void __fastcall rdo_ana_step_4Click(TObject *Sender);
	void __fastcall rdo_level_nx_3Click(TObject *Sender);
	void __fastcall rdo_ana_step_4_LRCClick(TObject *Sender);
	void __fastcall rdo_level_nx_3_LRCClick(TObject *Sender);
	void __fastcall CategoryPanel10Collapse(TObject *Sender);
	void __fastcall CategoryPanel10Expand(TObject *Sender);
	void __fastcall cmbEncoderCustomChange(TObject *Sender);
	void __fastcall edtEncoderCustomTitleChange(TObject *Sender);
	void __fastcall cmbEncoderCustomPgChange(TObject *Sender);
	void __fastcall cmbEncoderCustomExtChange(TObject *Sender);
	void __fastcall edtEncoderCustomParamChange(TObject *Sender);
	void __fastcall btnEncoderCustomSaveClick(TObject *Sender);
	void __fastcall btnEncoderCustomDeleteClick(TObject *Sender);



private:	// ユーザー宣言
	UnicodeString   rd_defaultParameterPath;
	UnicodeString   rd_defaultEQPath;
	UnicodeString   wr_defaultParameterPath;
	UnicodeString   wr_defaultEQPath;
	int				portableMode;
	int				changePortableMode;
	int				saveFlag;
	void __fastcall LoadDefaultParameter(void);
	void __fastcall SaveDefaultParameter(int index);
	void __fastcall ParseDefaultParameter(int index);
	void __fastcall ChangeHFAPreset(void);
	void __fastcall LoadEncoderCustomOption(int index);
	void __fastcall SaveEncoderCustomOption(int index);
public:		// ユーザー宣言
	__fastcall TForm1(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm1 *Form1;
//---------------------------------------------------------------------------
#endif
